@base = http://localhost:5207

### GET /now

GET {{base}}/now
Accept: application/json

### CreateOrder

POST {{base}}/order/create
Accept: application/json
Content-Type: application/json

{
  "RequestId": "03d5e4c8-a8bb-4249-b625-b53b43dfd0bf"
}