@base = http://localhost:5234

### GET /now

GET {{base}}/now
Accept: application/json

### CreateOrder

POST {{base}}/orders/create
Accept: application/json
Content-Type: application/json

{
  "request_id": "03d5e4c8-a8bb-4249-b625-b53b43dfd0bf"
}

### GetOrderQuery

POST {{base}}/orders/query
Accept: application/json
Content-Type: application/json

{
  "order_id": "aedf5acc-4b8c-4261-9090-ee549ef936be"
}

### PaymentReceived

POST {{base}}/orders/payment
Accept: application/json
Content-Type: application/json

{
  "order_id": "aedf5acc-4b8c-4261-9090-ee549ef936be"
}