@base = http://localhost:5234

### GET /now

GET {{base}}/now
Accept: application/json

### CreateOrder (but reject)

POST {{base}}/orders/create
Accept: application/json
Content-Type: application/json

{
  "requested_by": ""
}

### CreateOrder

POST {{base}}/orders/create
Accept: application/json
Content-Type: application/json

{
  "requested_by": "customer@brightsign.biz"
}

### PaymentReceived

POST {{base}}/payments/received
Accept: application/json
Content-Type: application/json

{
  "order_id": "f367bc03-3217-48f3-8ff9-a62bfcffd053"
}

### GetOrderQuery

POST {{base}}/orders/query
Accept: application/json
Content-Type: application/json

{
  "order_id": "f367bc03-3217-48f3-8ff9-a62bfcffd053"
}

