@base = http://localhost:5234

### Health

GET {{base}}/health

### CreateOrder

POST {{base}}/orders/create
Accept: application/json
Content-Type: application/json

{
  "requested_by": "customer@company.com"
}