name: k4os-nats-transit

services: 
  # app:
  #   image: ${DOCKER_IMAGE_PREFIX}/app:latest

  nats:
    image: nats:latest
    command: -js -m 8222
    ports:
      - "4222:4222" # client port
      - "8222:8222" # management port
    # volumes:
    #   - nats-js-data:/tmp/nats/jetstream

  pgsql:
    image: postgres:latest
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "Test!123"
    ports:
      - 5432:5432
        
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
  
  dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:8.1
    # image: snehapar9/aspire-dashboard:v19
    # image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
    ports:
      - 18888:18888
      - 4317:18889
