name: k4os-nats-transit

services: 
  # app:
  #   image: ${DOCKER_IMAGE_PREFIX}/app:latest

  nats:
    image: nats:latest
    command: -js -m 8222
    ports:
      - "4222:4222" # client port
      - "8222:8222" # management port
    # volumes:
    #   - nats-js-data:/tmp/nats/jetstream

  redis:
    image: redis
    entrypoint: redis-server
    command: --appendonly yes
    ports:
      - 6379:6379